const QINIU_ACCESSKEY = "MzrBdFaXcbyFkO84NEPdTh6o9-HN-VOIzm_e9b_2";
const QINIU_SECRETKEY = "zKaVLD3VDf7VHgx9Qmm1h0JNNUgQGJP9tzv6Sh7m";
const QINIU_BUCKET="develop"

export {
  QINIU_ACCESSKEY,
  QINIU_BUCKET,
  QINIU_SECRETKEY
}